name: CI/CD for Fashion Store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for backend
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Step 4: Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Step 5: Test backend (if tests exist)
      - name: Test Backend
        working-directory: ./backend
        run: npm test

      # Step 6: Test frontend (if tests exist)
      - name: Test Frontend
        working-directory: ./frontend
        run: npm test
